services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynet
    depends_on:
      - api-1
      - api-2

  api-1:
    build:
      context: ./MyFirstAotWebApi
    container_name: api-1
    tty: true
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8081
    networks:
      - mynet

  api-2:
    build:
      context: ./MyFirstAotWebApi
    container_name: api-2
    tty: true
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORT=8082
    networks:
      - mynet

networks:
  mynet:
    driver: bridge