name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change directories
      run: cd src/MyFirstAotWebApi/
    - name: Build image
      run: docker image build -t aot-calc:$(date +%s) .
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
